// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/dictionary.proto

package linguistglass

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DictionaryServiceClient is the client API for DictionaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DictionaryServiceClient interface {
	// SearchWords searches for words matching a query
	SearchWords(ctx context.Context, in *SearchWordsRequest, opts ...grpc.CallOption) (*WordListResponse, error)
	// GetWordDetail retrieves detailed information about a word
	GetWordDetail(ctx context.Context, in *GetWordDetailRequest, opts ...grpc.CallOption) (*WordDetailResponse, error)
	// CreateUserDictionary creates a new user dictionary
	CreateUserDictionary(ctx context.Context, in *CreateDictionaryRequest, opts ...grpc.CallOption) (*DictionaryResponse, error)
	// ListDictionaries retrieves dictionaries by level or user
	ListDictionaries(ctx context.Context, in *ListDictionariesRequest, opts ...grpc.CallOption) (*DictionaryListResponse, error)
	// AddWordToDictionary adds a word to a dictionary
	AddWordToDictionary(ctx context.Context, in *AddWordToDictionaryRequest, opts ...grpc.CallOption) (*DictionaryResponse, error)
}

type dictionaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDictionaryServiceClient(cc grpc.ClientConnInterface) DictionaryServiceClient {
	return &dictionaryServiceClient{cc}
}

func (c *dictionaryServiceClient) SearchWords(ctx context.Context, in *SearchWordsRequest, opts ...grpc.CallOption) (*WordListResponse, error) {
	out := new(WordListResponse)
	err := c.cc.Invoke(ctx, "/linguistglass.DictionaryService/SearchWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryServiceClient) GetWordDetail(ctx context.Context, in *GetWordDetailRequest, opts ...grpc.CallOption) (*WordDetailResponse, error) {
	out := new(WordDetailResponse)
	err := c.cc.Invoke(ctx, "/linguistglass.DictionaryService/GetWordDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryServiceClient) CreateUserDictionary(ctx context.Context, in *CreateDictionaryRequest, opts ...grpc.CallOption) (*DictionaryResponse, error) {
	out := new(DictionaryResponse)
	err := c.cc.Invoke(ctx, "/linguistglass.DictionaryService/CreateUserDictionary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryServiceClient) ListDictionaries(ctx context.Context, in *ListDictionariesRequest, opts ...grpc.CallOption) (*DictionaryListResponse, error) {
	out := new(DictionaryListResponse)
	err := c.cc.Invoke(ctx, "/linguistglass.DictionaryService/ListDictionaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryServiceClient) AddWordToDictionary(ctx context.Context, in *AddWordToDictionaryRequest, opts ...grpc.CallOption) (*DictionaryResponse, error) {
	out := new(DictionaryResponse)
	err := c.cc.Invoke(ctx, "/linguistglass.DictionaryService/AddWordToDictionary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictionaryServiceServer is the server API for DictionaryService service.
// All implementations must embed UnimplementedDictionaryServiceServer
// for forward compatibility
type DictionaryServiceServer interface {
	// SearchWords searches for words matching a query
	SearchWords(context.Context, *SearchWordsRequest) (*WordListResponse, error)
	// GetWordDetail retrieves detailed information about a word
	GetWordDetail(context.Context, *GetWordDetailRequest) (*WordDetailResponse, error)
	// CreateUserDictionary creates a new user dictionary
	CreateUserDictionary(context.Context, *CreateDictionaryRequest) (*DictionaryResponse, error)
	// ListDictionaries retrieves dictionaries by level or user
	ListDictionaries(context.Context, *ListDictionariesRequest) (*DictionaryListResponse, error)
	// AddWordToDictionary adds a word to a dictionary
	AddWordToDictionary(context.Context, *AddWordToDictionaryRequest) (*DictionaryResponse, error)
	mustEmbedUnimplementedDictionaryServiceServer()
}

// UnimplementedDictionaryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDictionaryServiceServer struct {
}

func (UnimplementedDictionaryServiceServer) SearchWords(context.Context, *SearchWordsRequest) (*WordListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchWords not implemented")
}
func (UnimplementedDictionaryServiceServer) GetWordDetail(context.Context, *GetWordDetailRequest) (*WordDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWordDetail not implemented")
}
func (UnimplementedDictionaryServiceServer) CreateUserDictionary(context.Context, *CreateDictionaryRequest) (*DictionaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserDictionary not implemented")
}
func (UnimplementedDictionaryServiceServer) ListDictionaries(context.Context, *ListDictionariesRequest) (*DictionaryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDictionaries not implemented")
}
func (UnimplementedDictionaryServiceServer) AddWordToDictionary(context.Context, *AddWordToDictionaryRequest) (*DictionaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWordToDictionary not implemented")
}
func (UnimplementedDictionaryServiceServer) mustEmbedUnimplementedDictionaryServiceServer() {}

// UnsafeDictionaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DictionaryServiceServer will
// result in compilation errors.
type UnsafeDictionaryServiceServer interface {
	mustEmbedUnimplementedDictionaryServiceServer()
}

func RegisterDictionaryServiceServer(s grpc.ServiceRegistrar, srv DictionaryServiceServer) {
	s.RegisterService(&DictionaryService_ServiceDesc, srv)
}

func _DictionaryService_SearchWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchWordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServiceServer).SearchWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/linguistglass.DictionaryService/SearchWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServiceServer).SearchWords(ctx, req.(*SearchWordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictionaryService_GetWordDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWordDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServiceServer).GetWordDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/linguistglass.DictionaryService/GetWordDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServiceServer).GetWordDetail(ctx, req.(*GetWordDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictionaryService_CreateUserDictionary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDictionaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServiceServer).CreateUserDictionary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/linguistglass.DictionaryService/CreateUserDictionary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServiceServer).CreateUserDictionary(ctx, req.(*CreateDictionaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictionaryService_ListDictionaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDictionariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServiceServer).ListDictionaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/linguistglass.DictionaryService/ListDictionaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServiceServer).ListDictionaries(ctx, req.(*ListDictionariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictionaryService_AddWordToDictionary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWordToDictionaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServiceServer).AddWordToDictionary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/linguistglass.DictionaryService/AddWordToDictionary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServiceServer).AddWordToDictionary(ctx, req.(*AddWordToDictionaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DictionaryService_ServiceDesc is the grpc.ServiceDesc for DictionaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DictionaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linguistglass.DictionaryService",
	HandlerType: (*DictionaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchWords",
			Handler:    _DictionaryService_SearchWords_Handler,
		},
		{
			MethodName: "GetWordDetail",
			Handler:    _DictionaryService_GetWordDetail_Handler,
		},
		{
			MethodName: "CreateUserDictionary",
			Handler:    _DictionaryService_CreateUserDictionary_Handler,
		},
		{
			MethodName: "ListDictionaries",
			Handler:    _DictionaryService_ListDictionaries_Handler,
		},
		{
			MethodName: "AddWordToDictionary",
			Handler:    _DictionaryService_AddWordToDictionary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dictionary.proto",
}
