// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/dictionary.proto

package linguistglass

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchWordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchWordsRequest) Reset() {
	*x = SearchWordsRequest{}
	mi := &file_proto_dictionary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchWordsRequest) ProtoMessage() {}

func (x *SearchWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchWordsRequest.ProtoReflect.Descriptor instead.
func (*SearchWordsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{0}
}

func (x *SearchWordsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchWordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetWordDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WordId        string                 `protobuf:"bytes,1,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordDetailRequest) Reset() {
	*x = GetWordDetailRequest{}
	mi := &file_proto_dictionary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordDetailRequest) ProtoMessage() {}

func (x *GetWordDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordDetailRequest.ProtoReflect.Descriptor instead.
func (*GetWordDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{1}
}

func (x *GetWordDetailRequest) GetWordId() string {
	if x != nil {
		return x.WordId
	}
	return ""
}

type CreateDictionaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // A1, A2, B1, B2, C1, C2
	IsPublic      bool                   `protobuf:"varint,3,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictionaryRequest) Reset() {
	*x = CreateDictionaryRequest{}
	mi := &file_proto_dictionary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictionaryRequest) ProtoMessage() {}

func (x *CreateDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictionaryRequest.ProtoReflect.Descriptor instead.
func (*CreateDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDictionaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDictionaryRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CreateDictionaryRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type ListDictionariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IncludePublic bool                   `protobuf:"varint,3,opt,name=include_public,json=includePublic,proto3" json:"include_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictionariesRequest) Reset() {
	*x = ListDictionariesRequest{}
	mi := &file_proto_dictionary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictionariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionariesRequest) ProtoMessage() {}

func (x *ListDictionariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionariesRequest.ProtoReflect.Descriptor instead.
func (*ListDictionariesRequest) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{3}
}

func (x *ListDictionariesRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ListDictionariesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListDictionariesRequest) GetIncludePublic() bool {
	if x != nil {
		return x.IncludePublic
	}
	return false
}

type AddWordToDictionaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictionaryId  string                 `protobuf:"bytes,1,opt,name=dictionary_id,json=dictionaryId,proto3" json:"dictionary_id,omitempty"`
	WordId        string                 `protobuf:"bytes,2,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWordToDictionaryRequest) Reset() {
	*x = AddWordToDictionaryRequest{}
	mi := &file_proto_dictionary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWordToDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWordToDictionaryRequest) ProtoMessage() {}

func (x *AddWordToDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWordToDictionaryRequest.ProtoReflect.Descriptor instead.
func (*AddWordToDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{4}
}

func (x *AddWordToDictionaryRequest) GetDictionaryId() string {
	if x != nil {
		return x.DictionaryId
	}
	return ""
}

func (x *AddWordToDictionaryRequest) GetWordId() string {
	if x != nil {
		return x.WordId
	}
	return ""
}

type Word struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Headword      string                 `protobuf:"bytes,2,opt,name=headword,proto3" json:"headword,omitempty"`
	PartOfSpeech  string                 `protobuf:"bytes,3,opt,name=part_of_speech,json=partOfSpeech,proto3" json:"part_of_speech,omitempty"`
	Transcription string                 `protobuf:"bytes,4,opt,name=transcription,proto3" json:"transcription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Word) Reset() {
	*x = Word{}
	mi := &file_proto_dictionary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{5}
}

func (x *Word) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Word) GetHeadword() string {
	if x != nil {
		return x.Headword
	}
	return ""
}

func (x *Word) GetPartOfSpeech() string {
	if x != nil {
		return x.PartOfSpeech
	}
	return ""
}

func (x *Word) GetTranscription() string {
	if x != nil {
		return x.Transcription
	}
	return ""
}

type Definition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WordId         string                 `protobuf:"bytes,2,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	Language       string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Text           string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	ContextualNote string                 `protobuf:"bytes,5,opt,name=contextual_note,json=contextualNote,proto3" json:"contextual_note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_proto_dictionary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{6}
}

func (x *Definition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Definition) GetWordId() string {
	if x != nil {
		return x.WordId
	}
	return ""
}

func (x *Definition) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Definition) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Definition) GetContextualNote() string {
	if x != nil {
		return x.ContextualNote
	}
	return ""
}

type Example struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WordId        string                 `protobuf:"bytes,2,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Translation   string                 `protobuf:"bytes,4,opt,name=translation,proto3" json:"translation,omitempty"`
	VideoSourceId *string                `protobuf:"bytes,5,opt,name=video_source_id,json=videoSourceId,proto3,oneof" json:"video_source_id,omitempty"`
	Timestamp     *int32                 `protobuf:"varint,6,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_proto_dictionary_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{7}
}

func (x *Example) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Example) GetWordId() string {
	if x != nil {
		return x.WordId
	}
	return ""
}

func (x *Example) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Example) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

func (x *Example) GetVideoSourceId() string {
	if x != nil && x.VideoSourceId != nil {
		return *x.VideoSourceId
	}
	return ""
}

func (x *Example) GetTimestamp() int32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type WordDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *Word                  `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Definitions   []*Definition          `protobuf:"bytes,2,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Examples      []*Example             `protobuf:"bytes,3,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordDetail) Reset() {
	*x = WordDetail{}
	mi := &file_proto_dictionary_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordDetail) ProtoMessage() {}

func (x *WordDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordDetail.ProtoReflect.Descriptor instead.
func (*WordDetail) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{8}
}

func (x *WordDetail) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

func (x *WordDetail) GetDefinitions() []*Definition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *WordDetail) GetExamples() []*Example {
	if x != nil {
		return x.Examples
	}
	return nil
}

type Dictionary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId     string                 `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	WordCount     int32                  `protobuf:"varint,6,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dictionary) Reset() {
	*x = Dictionary{}
	mi := &file_proto_dictionary_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dictionary) ProtoMessage() {}

func (x *Dictionary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dictionary.ProtoReflect.Descriptor instead.
func (*Dictionary) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{9}
}

func (x *Dictionary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dictionary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dictionary) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Dictionary) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Dictionary) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Dictionary) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

type WordListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Words         []*Word                `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordListResponse) Reset() {
	*x = WordListResponse{}
	mi := &file_proto_dictionary_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordListResponse) ProtoMessage() {}

func (x *WordListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordListResponse.ProtoReflect.Descriptor instead.
func (*WordListResponse) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{10}
}

func (x *WordListResponse) GetWords() []*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

type WordDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WordDetail    *WordDetail            `protobuf:"bytes,1,opt,name=word_detail,json=wordDetail,proto3" json:"word_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordDetailResponse) Reset() {
	*x = WordDetailResponse{}
	mi := &file_proto_dictionary_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordDetailResponse) ProtoMessage() {}

func (x *WordDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordDetailResponse.ProtoReflect.Descriptor instead.
func (*WordDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{11}
}

func (x *WordDetailResponse) GetWordDetail() *WordDetail {
	if x != nil {
		return x.WordDetail
	}
	return nil
}

type DictionaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dictionary    *Dictionary            `protobuf:"bytes,1,opt,name=dictionary,proto3" json:"dictionary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryResponse) Reset() {
	*x = DictionaryResponse{}
	mi := &file_proto_dictionary_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryResponse) ProtoMessage() {}

func (x *DictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryResponse.ProtoReflect.Descriptor instead.
func (*DictionaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{12}
}

func (x *DictionaryResponse) GetDictionary() *Dictionary {
	if x != nil {
		return x.Dictionary
	}
	return nil
}

type DictionaryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dictionaries  []*Dictionary          `protobuf:"bytes,1,rep,name=dictionaries,proto3" json:"dictionaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryListResponse) Reset() {
	*x = DictionaryListResponse{}
	mi := &file_proto_dictionary_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryListResponse) ProtoMessage() {}

func (x *DictionaryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dictionary_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryListResponse.ProtoReflect.Descriptor instead.
func (*DictionaryListResponse) Descriptor() ([]byte, []int) {
	return file_proto_dictionary_proto_rawDescGZIP(), []int{13}
}

func (x *DictionaryListResponse) GetDictionaries() []*Dictionary {
	if x != nil {
		return x.Dictionaries
	}
	return nil
}

var File_proto_dictionary_proto protoreflect.FileDescriptor

const file_proto_dictionary_proto_rawDesc = "" +
	"\n" +
	"\x16proto/dictionary.proto\x12\rlinguistglass\"@\n" +
	"\x12SearchWordsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"/\n" +
	"\x14GetWordDetailRequest\x12\x17\n" +
	"\aword_id\x18\x01 \x01(\tR\x06wordId\"`\n" +
	"\x17CreateDictionaryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x1b\n" +
	"\tis_public\x18\x03 \x01(\bR\bisPublic\"o\n" +
	"\x17ListDictionariesRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0einclude_public\x18\x03 \x01(\bR\rincludePublic\"Z\n" +
	"\x1aAddWordToDictionaryRequest\x12#\n" +
	"\rdictionary_id\x18\x01 \x01(\tR\fdictionaryId\x12\x17\n" +
	"\aword_id\x18\x02 \x01(\tR\x06wordId\"~\n" +
	"\x04Word\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bheadword\x18\x02 \x01(\tR\bheadword\x12$\n" +
	"\x0epart_of_speech\x18\x03 \x01(\tR\fpartOfSpeech\x12$\n" +
	"\rtranscription\x18\x04 \x01(\tR\rtranscription\"\x8e\x01\n" +
	"\n" +
	"Definition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aword_id\x18\x02 \x01(\tR\x06wordId\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12'\n" +
	"\x0fcontextual_note\x18\x05 \x01(\tR\x0econtextualNote\"\xda\x01\n" +
	"\aExample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aword_id\x18\x02 \x01(\tR\x06wordId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12 \n" +
	"\vtranslation\x18\x04 \x01(\tR\vtranslation\x12+\n" +
	"\x0fvideo_source_id\x18\x05 \x01(\tH\x00R\rvideoSourceId\x88\x01\x01\x12!\n" +
	"\ttimestamp\x18\x06 \x01(\x05H\x01R\ttimestamp\x88\x01\x01B\x12\n" +
	"\x10_video_source_idB\f\n" +
	"\n" +
	"_timestamp\"\xa6\x01\n" +
	"\n" +
	"WordDetail\x12'\n" +
	"\x04word\x18\x01 \x01(\v2\x13.linguistglass.WordR\x04word\x12;\n" +
	"\vdefinitions\x18\x02 \x03(\v2\x19.linguistglass.DefinitionR\vdefinitions\x122\n" +
	"\bexamples\x18\x03 \x03(\v2\x16.linguistglass.ExampleR\bexamples\"\xa1\x01\n" +
	"\n" +
	"Dictionary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\tR\tcreatorId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x12\x1d\n" +
	"\n" +
	"word_count\x18\x06 \x01(\x05R\twordCount\"=\n" +
	"\x10WordListResponse\x12)\n" +
	"\x05words\x18\x01 \x03(\v2\x13.linguistglass.WordR\x05words\"P\n" +
	"\x12WordDetailResponse\x12:\n" +
	"\vword_detail\x18\x01 \x01(\v2\x19.linguistglass.WordDetailR\n" +
	"wordDetail\"O\n" +
	"\x12DictionaryResponse\x129\n" +
	"\n" +
	"dictionary\x18\x01 \x01(\v2\x19.linguistglass.DictionaryR\n" +
	"dictionary\"W\n" +
	"\x16DictionaryListResponse\x12=\n" +
	"\fdictionaries\x18\x01 \x03(\v2\x19.linguistglass.DictionaryR\fdictionaries2\xea\x03\n" +
	"\x11DictionaryService\x12Q\n" +
	"\vSearchWords\x12!.linguistglass.SearchWordsRequest\x1a\x1f.linguistglass.WordListResponse\x12W\n" +
	"\rGetWordDetail\x12#.linguistglass.GetWordDetailRequest\x1a!.linguistglass.WordDetailResponse\x12a\n" +
	"\x14CreateUserDictionary\x12&.linguistglass.CreateDictionaryRequest\x1a!.linguistglass.DictionaryResponse\x12a\n" +
	"\x10ListDictionaries\x12&.linguistglass.ListDictionariesRequest\x1a%.linguistglass.DictionaryListResponse\x12c\n" +
	"\x13AddWordToDictionary\x12).linguistglass.AddWordToDictionaryRequest\x1a!.linguistglass.DictionaryResponseB0Z.github.com/mabramyan/langgrpc/go/linguistglassb\x06proto3"

var (
	file_proto_dictionary_proto_rawDescOnce sync.Once
	file_proto_dictionary_proto_rawDescData []byte
)

func file_proto_dictionary_proto_rawDescGZIP() []byte {
	file_proto_dictionary_proto_rawDescOnce.Do(func() {
		file_proto_dictionary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dictionary_proto_rawDesc), len(file_proto_dictionary_proto_rawDesc)))
	})
	return file_proto_dictionary_proto_rawDescData
}

var file_proto_dictionary_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_dictionary_proto_goTypes = []any{
	(*SearchWordsRequest)(nil),         // 0: linguistglass.SearchWordsRequest
	(*GetWordDetailRequest)(nil),       // 1: linguistglass.GetWordDetailRequest
	(*CreateDictionaryRequest)(nil),    // 2: linguistglass.CreateDictionaryRequest
	(*ListDictionariesRequest)(nil),    // 3: linguistglass.ListDictionariesRequest
	(*AddWordToDictionaryRequest)(nil), // 4: linguistglass.AddWordToDictionaryRequest
	(*Word)(nil),                       // 5: linguistglass.Word
	(*Definition)(nil),                 // 6: linguistglass.Definition
	(*Example)(nil),                    // 7: linguistglass.Example
	(*WordDetail)(nil),                 // 8: linguistglass.WordDetail
	(*Dictionary)(nil),                 // 9: linguistglass.Dictionary
	(*WordListResponse)(nil),           // 10: linguistglass.WordListResponse
	(*WordDetailResponse)(nil),         // 11: linguistglass.WordDetailResponse
	(*DictionaryResponse)(nil),         // 12: linguistglass.DictionaryResponse
	(*DictionaryListResponse)(nil),     // 13: linguistglass.DictionaryListResponse
}
var file_proto_dictionary_proto_depIdxs = []int32{
	5,  // 0: linguistglass.WordDetail.word:type_name -> linguistglass.Word
	6,  // 1: linguistglass.WordDetail.definitions:type_name -> linguistglass.Definition
	7,  // 2: linguistglass.WordDetail.examples:type_name -> linguistglass.Example
	5,  // 3: linguistglass.WordListResponse.words:type_name -> linguistglass.Word
	8,  // 4: linguistglass.WordDetailResponse.word_detail:type_name -> linguistglass.WordDetail
	9,  // 5: linguistglass.DictionaryResponse.dictionary:type_name -> linguistglass.Dictionary
	9,  // 6: linguistglass.DictionaryListResponse.dictionaries:type_name -> linguistglass.Dictionary
	0,  // 7: linguistglass.DictionaryService.SearchWords:input_type -> linguistglass.SearchWordsRequest
	1,  // 8: linguistglass.DictionaryService.GetWordDetail:input_type -> linguistglass.GetWordDetailRequest
	2,  // 9: linguistglass.DictionaryService.CreateUserDictionary:input_type -> linguistglass.CreateDictionaryRequest
	3,  // 10: linguistglass.DictionaryService.ListDictionaries:input_type -> linguistglass.ListDictionariesRequest
	4,  // 11: linguistglass.DictionaryService.AddWordToDictionary:input_type -> linguistglass.AddWordToDictionaryRequest
	10, // 12: linguistglass.DictionaryService.SearchWords:output_type -> linguistglass.WordListResponse
	11, // 13: linguistglass.DictionaryService.GetWordDetail:output_type -> linguistglass.WordDetailResponse
	12, // 14: linguistglass.DictionaryService.CreateUserDictionary:output_type -> linguistglass.DictionaryResponse
	13, // 15: linguistglass.DictionaryService.ListDictionaries:output_type -> linguistglass.DictionaryListResponse
	12, // 16: linguistglass.DictionaryService.AddWordToDictionary:output_type -> linguistglass.DictionaryResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_dictionary_proto_init() }
func file_proto_dictionary_proto_init() {
	if File_proto_dictionary_proto != nil {
		return
	}
	file_proto_dictionary_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dictionary_proto_rawDesc), len(file_proto_dictionary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dictionary_proto_goTypes,
		DependencyIndexes: file_proto_dictionary_proto_depIdxs,
		MessageInfos:      file_proto_dictionary_proto_msgTypes,
	}.Build()
	File_proto_dictionary_proto = out.File
	file_proto_dictionary_proto_goTypes = nil
	file_proto_dictionary_proto_depIdxs = nil
}
