// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/study.proto

package linguistglass

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StudyService_GetDailySession_FullMethodName     = "/linguistglass.StudyService/GetDailySession"
	StudyService_SubmitStudyResult_FullMethodName   = "/linguistglass.StudyService/SubmitStudyResult"
	StudyService_AddWordToFlashcards_FullMethodName = "/linguistglass.StudyService/AddWordToFlashcards"
	StudyService_SyncProgress_FullMethodName        = "/linguistglass.StudyService/SyncProgress"
	StudyService_GetStats_FullMethodName            = "/linguistglass.StudyService/GetStats"
)

// StudyServiceClient is the client API for StudyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StudyService handles flashcards and spaced repetition
type StudyServiceClient interface {
	// GetDailySession retrieves cards due for review today
	GetDailySession(ctx context.Context, in *GetDailySessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	// SubmitStudyResult submits a card review result
	SubmitStudyResult(ctx context.Context, in *SubmitStudyResultRequest, opts ...grpc.CallOption) (*StudyResultResponse, error)
	// AddWordToFlashcards creates a new flashcard from a word
	AddWordToFlashcards(ctx context.Context, in *AddWordToFlashcardsRequest, opts ...grpc.CallOption) (*CardResponse, error)
	// SyncProgress synchronizes study progress (offline support)
	SyncProgress(ctx context.Context, in *SyncProgressRequest, opts ...grpc.CallOption) (*SyncProgressResponse, error)
	// GetStats retrieves user study statistics
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type studyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudyServiceClient(cc grpc.ClientConnInterface) StudyServiceClient {
	return &studyServiceClient{cc}
}

func (c *studyServiceClient) GetDailySession(ctx context.Context, in *GetDailySessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, StudyService_GetDailySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceClient) SubmitStudyResult(ctx context.Context, in *SubmitStudyResultRequest, opts ...grpc.CallOption) (*StudyResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudyResultResponse)
	err := c.cc.Invoke(ctx, StudyService_SubmitStudyResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceClient) AddWordToFlashcards(ctx context.Context, in *AddWordToFlashcardsRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, StudyService_AddWordToFlashcards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceClient) SyncProgress(ctx context.Context, in *SyncProgressRequest, opts ...grpc.CallOption) (*SyncProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncProgressResponse)
	err := c.cc.Invoke(ctx, StudyService_SyncProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, StudyService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudyServiceServer is the server API for StudyService service.
// All implementations must embed UnimplementedStudyServiceServer
// for forward compatibility.
//
// StudyService handles flashcards and spaced repetition
type StudyServiceServer interface {
	// GetDailySession retrieves cards due for review today
	GetDailySession(context.Context, *GetDailySessionRequest) (*SessionResponse, error)
	// SubmitStudyResult submits a card review result
	SubmitStudyResult(context.Context, *SubmitStudyResultRequest) (*StudyResultResponse, error)
	// AddWordToFlashcards creates a new flashcard from a word
	AddWordToFlashcards(context.Context, *AddWordToFlashcardsRequest) (*CardResponse, error)
	// SyncProgress synchronizes study progress (offline support)
	SyncProgress(context.Context, *SyncProgressRequest) (*SyncProgressResponse, error)
	// GetStats retrieves user study statistics
	GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedStudyServiceServer()
}

// UnimplementedStudyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStudyServiceServer struct{}

func (UnimplementedStudyServiceServer) GetDailySession(context.Context, *GetDailySessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailySession not implemented")
}
func (UnimplementedStudyServiceServer) SubmitStudyResult(context.Context, *SubmitStudyResultRequest) (*StudyResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitStudyResult not implemented")
}
func (UnimplementedStudyServiceServer) AddWordToFlashcards(context.Context, *AddWordToFlashcardsRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWordToFlashcards not implemented")
}
func (UnimplementedStudyServiceServer) SyncProgress(context.Context, *SyncProgressRequest) (*SyncProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncProgress not implemented")
}
func (UnimplementedStudyServiceServer) GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedStudyServiceServer) mustEmbedUnimplementedStudyServiceServer() {}
func (UnimplementedStudyServiceServer) testEmbeddedByValue()                      {}

// UnsafeStudyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudyServiceServer will
// result in compilation errors.
type UnsafeStudyServiceServer interface {
	mustEmbedUnimplementedStudyServiceServer()
}

func RegisterStudyServiceServer(s grpc.ServiceRegistrar, srv StudyServiceServer) {
	// If the following call panics, it indicates UnimplementedStudyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StudyService_ServiceDesc, srv)
}

func _StudyService_GetDailySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).GetDailySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_GetDailySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).GetDailySession(ctx, req.(*GetDailySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyService_SubmitStudyResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitStudyResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).SubmitStudyResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_SubmitStudyResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).SubmitStudyResult(ctx, req.(*SubmitStudyResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyService_AddWordToFlashcards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWordToFlashcardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).AddWordToFlashcards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_AddWordToFlashcards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).AddWordToFlashcards(ctx, req.(*AddWordToFlashcardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyService_SyncProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).SyncProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_SyncProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).SyncProgress(ctx, req.(*SyncProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudyService_ServiceDesc is the grpc.ServiceDesc for StudyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linguistglass.StudyService",
	HandlerType: (*StudyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailySession",
			Handler:    _StudyService_GetDailySession_Handler,
		},
		{
			MethodName: "SubmitStudyResult",
			Handler:    _StudyService_SubmitStudyResult_Handler,
		},
		{
			MethodName: "AddWordToFlashcards",
			Handler:    _StudyService_AddWordToFlashcards_Handler,
		},
		{
			MethodName: "SyncProgress",
			Handler:    _StudyService_SyncProgress_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _StudyService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/study.proto",
}
