// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/study.proto

package linguistglass

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDailySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailySessionRequest) Reset() {
	*x = GetDailySessionRequest{}
	mi := &file_proto_study_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySessionRequest) ProtoMessage() {}

func (x *GetDailySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySessionRequest.ProtoReflect.Descriptor instead.
func (*GetDailySessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{0}
}

func (x *GetDailySessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDailySessionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SubmitStudyResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quality       int32                  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`                               // 0-5: 0-2=again, 3=hard, 4-5=easy
	ContextBonus  bool                   `protobuf:"varint,4,opt,name=context_bonus,json=contextBonus,proto3" json:"context_bonus,omitempty"` // Watched video context
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitStudyResultRequest) Reset() {
	*x = SubmitStudyResultRequest{}
	mi := &file_proto_study_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitStudyResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitStudyResultRequest) ProtoMessage() {}

func (x *SubmitStudyResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitStudyResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitStudyResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitStudyResultRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *SubmitStudyResultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitStudyResultRequest) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *SubmitStudyResultRequest) GetContextBonus() bool {
	if x != nil {
		return x.ContextBonus
	}
	return false
}

func (x *SubmitStudyResultRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AddWordToFlashcardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WordId        string                 `protobuf:"bytes,2,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	DictionaryId  string                 `protobuf:"bytes,3,opt,name=dictionary_id,json=dictionaryId,proto3" json:"dictionary_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWordToFlashcardsRequest) Reset() {
	*x = AddWordToFlashcardsRequest{}
	mi := &file_proto_study_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWordToFlashcardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWordToFlashcardsRequest) ProtoMessage() {}

func (x *AddWordToFlashcardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWordToFlashcardsRequest.ProtoReflect.Descriptor instead.
func (*AddWordToFlashcardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{2}
}

func (x *AddWordToFlashcardsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddWordToFlashcardsRequest) GetWordId() string {
	if x != nil {
		return x.WordId
	}
	return ""
}

func (x *AddWordToFlashcardsRequest) GetDictionaryId() string {
	if x != nil {
		return x.DictionaryId
	}
	return ""
}

type SyncProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Logs          []*StudyLogEntry       `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncProgressRequest) Reset() {
	*x = SyncProgressRequest{}
	mi := &file_proto_study_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncProgressRequest) ProtoMessage() {}

func (x *SyncProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncProgressRequest.ProtoReflect.Descriptor instead.
func (*SyncProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{3}
}

func (x *SyncProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncProgressRequest) GetLogs() []*StudyLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"` // Number of days to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_study_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStatsRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DictionaryId  string                 `protobuf:"bytes,3,opt,name=dictionary_id,json=dictionaryId,proto3" json:"dictionary_id,omitempty"`
	WordId        string                 `protobuf:"bytes,4,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // new, learning, review, mastered
	EaseFactor    float64                `protobuf:"fixed64,6,opt,name=ease_factor,json=easeFactor,proto3" json:"ease_factor,omitempty"`
	Interval      int32                  `protobuf:"varint,7,opt,name=interval,proto3" json:"interval,omitempty"`
	Repetitions   int32                  `protobuf:"varint,8,opt,name=repetitions,proto3" json:"repetitions,omitempty"`
	NextReviewAt  int64                  `protobuf:"varint,9,opt,name=next_review_at,json=nextReviewAt,proto3" json:"next_review_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_proto_study_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{5}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Card) GetDictionaryId() string {
	if x != nil {
		return x.DictionaryId
	}
	return ""
}

func (x *Card) GetWordId() string {
	if x != nil {
		return x.WordId
	}
	return ""
}

func (x *Card) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Card) GetEaseFactor() float64 {
	if x != nil {
		return x.EaseFactor
	}
	return 0
}

func (x *Card) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *Card) GetRepetitions() int32 {
	if x != nil {
		return x.Repetitions
	}
	return 0
}

func (x *Card) GetNextReviewAt() int64 {
	if x != nil {
		return x.NextReviewAt
	}
	return 0
}

type StudyLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CardId        string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Quality       int32                  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyLogEntry) Reset() {
	*x = StudyLogEntry{}
	mi := &file_proto_study_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyLogEntry) ProtoMessage() {}

func (x *StudyLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyLogEntry.ProtoReflect.Descriptor instead.
func (*StudyLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{6}
}

func (x *StudyLogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudyLogEntry) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *StudyLogEntry) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *StudyLogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DailyStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Date             string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	WordsLearned     int32                  `protobuf:"varint,2,opt,name=words_learned,json=wordsLearned,proto3" json:"words_learned,omitempty"`
	TimeSpentMinutes int32                  `protobuf:"varint,3,opt,name=time_spent_minutes,json=timeSpentMinutes,proto3" json:"time_spent_minutes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DailyStats) Reset() {
	*x = DailyStats{}
	mi := &file_proto_study_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStats) ProtoMessage() {}

func (x *DailyStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStats.ProtoReflect.Descriptor instead.
func (*DailyStats) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{7}
}

func (x *DailyStats) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStats) GetWordsLearned() int32 {
	if x != nil {
		return x.WordsLearned
	}
	return 0
}

func (x *DailyStats) GetTimeSpentMinutes() int32 {
	if x != nil {
		return x.TimeSpentMinutes
	}
	return 0
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	TotalDue      int32                  `protobuf:"varint,2,opt,name=total_due,json=totalDue,proto3" json:"total_due,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_proto_study_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{8}
}

func (x *SessionResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *SessionResponse) GetTotalDue() int32 {
	if x != nil {
		return x.TotalDue
	}
	return 0
}

type StudyResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	XpEarned      int32                  `protobuf:"varint,2,opt,name=xp_earned,json=xpEarned,proto3" json:"xp_earned,omitempty"`
	LeveledUp     bool                   `protobuf:"varint,3,opt,name=leveled_up,json=leveledUp,proto3" json:"leveled_up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyResultResponse) Reset() {
	*x = StudyResultResponse{}
	mi := &file_proto_study_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyResultResponse) ProtoMessage() {}

func (x *StudyResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyResultResponse.ProtoReflect.Descriptor instead.
func (*StudyResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{9}
}

func (x *StudyResultResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *StudyResultResponse) GetXpEarned() int32 {
	if x != nil {
		return x.XpEarned
	}
	return 0
}

func (x *StudyResultResponse) GetLeveledUp() bool {
	if x != nil {
		return x.LeveledUp
	}
	return false
}

type CardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_proto_study_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{10}
}

func (x *CardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type SyncProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ConflictIds   []string               `protobuf:"bytes,2,rep,name=conflict_ids,json=conflictIds,proto3" json:"conflict_ids,omitempty"` // Cards with conflicts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncProgressResponse) Reset() {
	*x = SyncProgressResponse{}
	mi := &file_proto_study_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncProgressResponse) ProtoMessage() {}

func (x *SyncProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncProgressResponse.ProtoReflect.Descriptor instead.
func (*SyncProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{11}
}

func (x *SyncProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncProgressResponse) GetConflictIds() []string {
	if x != nil {
		return x.ConflictIds
	}
	return nil
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentStreak int32                  `protobuf:"varint,1,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	TotalXp       int32                  `protobuf:"varint,2,opt,name=total_xp,json=totalXp,proto3" json:"total_xp,omitempty"`
	WordsLearned  int32                  `protobuf:"varint,3,opt,name=words_learned,json=wordsLearned,proto3" json:"words_learned,omitempty"`
	WordsMastered int32                  `protobuf:"varint,4,opt,name=words_mastered,json=wordsMastered,proto3" json:"words_mastered,omitempty"`
	DailyStats    []*DailyStats          `protobuf:"bytes,5,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_study_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_study_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_study_proto_rawDescGZIP(), []int{12}
}

func (x *StatsResponse) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *StatsResponse) GetTotalXp() int32 {
	if x != nil {
		return x.TotalXp
	}
	return 0
}

func (x *StatsResponse) GetWordsLearned() int32 {
	if x != nil {
		return x.WordsLearned
	}
	return 0
}

func (x *StatsResponse) GetWordsMastered() int32 {
	if x != nil {
		return x.WordsMastered
	}
	return 0
}

func (x *StatsResponse) GetDailyStats() []*DailyStats {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

var File_proto_study_proto protoreflect.FileDescriptor

const file_proto_study_proto_rawDesc = "" +
	"\n" +
	"\x11proto/study.proto\x12\rlinguistglass\"G\n" +
	"\x16GetDailySessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xa9\x01\n" +
	"\x18SubmitStudyResultRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\x12#\n" +
	"\rcontext_bonus\x18\x04 \x01(\bR\fcontextBonus\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"s\n" +
	"\x1aAddWordToFlashcardsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aword_id\x18\x02 \x01(\tR\x06wordId\x12#\n" +
	"\rdictionary_id\x18\x03 \x01(\tR\fdictionaryId\"`\n" +
	"\x13SyncProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x04logs\x18\x02 \x03(\v2\x1c.linguistglass.StudyLogEntryR\x04logs\">\n" +
	"\x0fGetStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\"\x8a\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rdictionary_id\x18\x03 \x01(\tR\fdictionaryId\x12\x17\n" +
	"\aword_id\x18\x04 \x01(\tR\x06wordId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vease_factor\x18\x06 \x01(\x01R\n" +
	"easeFactor\x12\x1a\n" +
	"\binterval\x18\a \x01(\x05R\binterval\x12 \n" +
	"\vrepetitions\x18\b \x01(\x05R\vrepetitions\x12$\n" +
	"\x0enext_review_at\x18\t \x01(\x03R\fnextReviewAt\"p\n" +
	"\rStudyLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"s\n" +
	"\n" +
	"DailyStats\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12#\n" +
	"\rwords_learned\x18\x02 \x01(\x05R\fwordsLearned\x12,\n" +
	"\x12time_spent_minutes\x18\x03 \x01(\x05R\x10timeSpentMinutes\"Y\n" +
	"\x0fSessionResponse\x12)\n" +
	"\x05cards\x18\x01 \x03(\v2\x13.linguistglass.CardR\x05cards\x12\x1b\n" +
	"\ttotal_due\x18\x02 \x01(\x05R\btotalDue\"z\n" +
	"\x13StudyResultResponse\x12'\n" +
	"\x04card\x18\x01 \x01(\v2\x13.linguistglass.CardR\x04card\x12\x1b\n" +
	"\txp_earned\x18\x02 \x01(\x05R\bxpEarned\x12\x1d\n" +
	"\n" +
	"leveled_up\x18\x03 \x01(\bR\tleveledUp\"7\n" +
	"\fCardResponse\x12'\n" +
	"\x04card\x18\x01 \x01(\v2\x13.linguistglass.CardR\x04card\"S\n" +
	"\x14SyncProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fconflict_ids\x18\x02 \x03(\tR\vconflictIds\"\xd9\x01\n" +
	"\rStatsResponse\x12%\n" +
	"\x0ecurrent_streak\x18\x01 \x01(\x05R\rcurrentStreak\x12\x19\n" +
	"\btotal_xp\x18\x02 \x01(\x05R\atotalXp\x12#\n" +
	"\rwords_learned\x18\x03 \x01(\x05R\fwordsLearned\x12%\n" +
	"\x0ewords_mastered\x18\x04 \x01(\x05R\rwordsMastered\x12:\n" +
	"\vdaily_stats\x18\x05 \x03(\v2\x19.linguistglass.DailyStatsR\n" +
	"dailyStats2\xcc\x03\n" +
	"\fStudyService\x12X\n" +
	"\x0fGetDailySession\x12%.linguistglass.GetDailySessionRequest\x1a\x1e.linguistglass.SessionResponse\x12`\n" +
	"\x11SubmitStudyResult\x12'.linguistglass.SubmitStudyResultRequest\x1a\".linguistglass.StudyResultResponse\x12]\n" +
	"\x13AddWordToFlashcards\x12).linguistglass.AddWordToFlashcardsRequest\x1a\x1b.linguistglass.CardResponse\x12W\n" +
	"\fSyncProgress\x12\".linguistglass.SyncProgressRequest\x1a#.linguistglass.SyncProgressResponse\x12H\n" +
	"\bGetStats\x12\x1e.linguistglass.GetStatsRequest\x1a\x1c.linguistglass.StatsResponseB0Z.github.com/mabramyan/langgrpc/go/linguistglassb\x06proto3"

var (
	file_proto_study_proto_rawDescOnce sync.Once
	file_proto_study_proto_rawDescData []byte
)

func file_proto_study_proto_rawDescGZIP() []byte {
	file_proto_study_proto_rawDescOnce.Do(func() {
		file_proto_study_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_study_proto_rawDesc), len(file_proto_study_proto_rawDesc)))
	})
	return file_proto_study_proto_rawDescData
}

var file_proto_study_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_study_proto_goTypes = []any{
	(*GetDailySessionRequest)(nil),     // 0: linguistglass.GetDailySessionRequest
	(*SubmitStudyResultRequest)(nil),   // 1: linguistglass.SubmitStudyResultRequest
	(*AddWordToFlashcardsRequest)(nil), // 2: linguistglass.AddWordToFlashcardsRequest
	(*SyncProgressRequest)(nil),        // 3: linguistglass.SyncProgressRequest
	(*GetStatsRequest)(nil),            // 4: linguistglass.GetStatsRequest
	(*Card)(nil),                       // 5: linguistglass.Card
	(*StudyLogEntry)(nil),              // 6: linguistglass.StudyLogEntry
	(*DailyStats)(nil),                 // 7: linguistglass.DailyStats
	(*SessionResponse)(nil),            // 8: linguistglass.SessionResponse
	(*StudyResultResponse)(nil),        // 9: linguistglass.StudyResultResponse
	(*CardResponse)(nil),               // 10: linguistglass.CardResponse
	(*SyncProgressResponse)(nil),       // 11: linguistglass.SyncProgressResponse
	(*StatsResponse)(nil),              // 12: linguistglass.StatsResponse
}
var file_proto_study_proto_depIdxs = []int32{
	6,  // 0: linguistglass.SyncProgressRequest.logs:type_name -> linguistglass.StudyLogEntry
	5,  // 1: linguistglass.SessionResponse.cards:type_name -> linguistglass.Card
	5,  // 2: linguistglass.StudyResultResponse.card:type_name -> linguistglass.Card
	5,  // 3: linguistglass.CardResponse.card:type_name -> linguistglass.Card
	7,  // 4: linguistglass.StatsResponse.daily_stats:type_name -> linguistglass.DailyStats
	0,  // 5: linguistglass.StudyService.GetDailySession:input_type -> linguistglass.GetDailySessionRequest
	1,  // 6: linguistglass.StudyService.SubmitStudyResult:input_type -> linguistglass.SubmitStudyResultRequest
	2,  // 7: linguistglass.StudyService.AddWordToFlashcards:input_type -> linguistglass.AddWordToFlashcardsRequest
	3,  // 8: linguistglass.StudyService.SyncProgress:input_type -> linguistglass.SyncProgressRequest
	4,  // 9: linguistglass.StudyService.GetStats:input_type -> linguistglass.GetStatsRequest
	8,  // 10: linguistglass.StudyService.GetDailySession:output_type -> linguistglass.SessionResponse
	9,  // 11: linguistglass.StudyService.SubmitStudyResult:output_type -> linguistglass.StudyResultResponse
	10, // 12: linguistglass.StudyService.AddWordToFlashcards:output_type -> linguistglass.CardResponse
	11, // 13: linguistglass.StudyService.SyncProgress:output_type -> linguistglass.SyncProgressResponse
	12, // 14: linguistglass.StudyService.GetStats:output_type -> linguistglass.StatsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_study_proto_init() }
func file_proto_study_proto_init() {
	if File_proto_study_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_study_proto_rawDesc), len(file_proto_study_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_study_proto_goTypes,
		DependencyIndexes: file_proto_study_proto_depIdxs,
		MessageInfos:      file_proto_study_proto_msgTypes,
	}.Build()
	File_proto_study_proto = out.File
	file_proto_study_proto_goTypes = nil
	file_proto_study_proto_depIdxs = nil
}
