// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/video.proto

package linguistglass

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindSentencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSentencesRequest) Reset() {
	*x = FindSentencesRequest{}
	mi := &file_proto_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSentencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSentencesRequest) ProtoMessage() {}

func (x *FindSentencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSentencesRequest.ProtoReflect.Descriptor instead.
func (*FindSentencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{0}
}

func (x *FindSentencesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *FindSentencesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ShadowingProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WordId        string                 `protobuf:"bytes,2,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	Accuracy      float32                `protobuf:"fixed32,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"` // 0.0 - 1.0
	Attempts      int32                  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowingProgressRequest) Reset() {
	*x = ShadowingProgressRequest{}
	mi := &file_proto_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowingProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowingProgressRequest) ProtoMessage() {}

func (x *ShadowingProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowingProgressRequest.ProtoReflect.Descriptor instead.
func (*ShadowingProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{1}
}

func (x *ShadowingProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShadowingProgressRequest) GetWordId() string {
	if x != nil {
		return x.WordId
	}
	return ""
}

func (x *ShadowingProgressRequest) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *ShadowingProgressRequest) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *ShadowingProgressRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type VideoClip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	StartTime     int32                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Seconds
	EndTime       int32                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SubtitleEn    string                 `protobuf:"bytes,6,opt,name=subtitle_en,json=subtitleEn,proto3" json:"subtitle_en,omitempty"`
	SubtitleRu    string                 `protobuf:"bytes,7,opt,name=subtitle_ru,json=subtitleRu,proto3" json:"subtitle_ru,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,8,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoClip) Reset() {
	*x = VideoClip{}
	mi := &file_proto_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoClip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoClip) ProtoMessage() {}

func (x *VideoClip) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoClip.ProtoReflect.Descriptor instead.
func (*VideoClip) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{2}
}

func (x *VideoClip) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoClip) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoClip) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *VideoClip) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *VideoClip) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *VideoClip) GetSubtitleEn() string {
	if x != nil {
		return x.SubtitleEn
	}
	return ""
}

func (x *VideoClip) GetSubtitleRu() string {
	if x != nil {
		return x.SubtitleRu
	}
	return ""
}

func (x *VideoClip) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type ShadowingFeedback struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OverallAccuracy float32                `protobuf:"fixed32,1,opt,name=overall_accuracy,json=overallAccuracy,proto3" json:"overall_accuracy,omitempty"`
	WordAccuracies  []*WordAccuracy        `protobuf:"bytes,2,rep,name=word_accuracies,json=wordAccuracies,proto3" json:"word_accuracies,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShadowingFeedback) Reset() {
	*x = ShadowingFeedback{}
	mi := &file_proto_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowingFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowingFeedback) ProtoMessage() {}

func (x *ShadowingFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowingFeedback.ProtoReflect.Descriptor instead.
func (*ShadowingFeedback) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{3}
}

func (x *ShadowingFeedback) GetOverallAccuracy() float32 {
	if x != nil {
		return x.OverallAccuracy
	}
	return 0
}

func (x *ShadowingFeedback) GetWordAccuracies() []*WordAccuracy {
	if x != nil {
		return x.WordAccuracies
	}
	return nil
}

type WordAccuracy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Accuracy      float32                `protobuf:"fixed32,2,opt,name=accuracy,proto3" json:"accuracy,omitempty"` // 0.0 - 1.0
	Feedback      string                 `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`   // "good", "needs_improvement", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordAccuracy) Reset() {
	*x = WordAccuracy{}
	mi := &file_proto_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordAccuracy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordAccuracy) ProtoMessage() {}

func (x *WordAccuracy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordAccuracy.ProtoReflect.Descriptor instead.
func (*WordAccuracy) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{4}
}

func (x *WordAccuracy) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordAccuracy) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *WordAccuracy) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

type VideoClipListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clips         []*VideoClip           `protobuf:"bytes,1,rep,name=clips,proto3" json:"clips,omitempty"`
	TotalResults  int32                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoClipListResponse) Reset() {
	*x = VideoClipListResponse{}
	mi := &file_proto_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoClipListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoClipListResponse) ProtoMessage() {}

func (x *VideoClipListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoClipListResponse.ProtoReflect.Descriptor instead.
func (*VideoClipListResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{5}
}

func (x *VideoClipListResponse) GetClips() []*VideoClip {
	if x != nil {
		return x.Clips
	}
	return nil
}

func (x *VideoClipListResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

type ShadowingFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      *ShadowingFeedback     `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XpEarned      int32                  `protobuf:"varint,2,opt,name=xp_earned,json=xpEarned,proto3" json:"xp_earned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowingFeedbackResponse) Reset() {
	*x = ShadowingFeedbackResponse{}
	mi := &file_proto_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowingFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowingFeedbackResponse) ProtoMessage() {}

func (x *ShadowingFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowingFeedbackResponse.ProtoReflect.Descriptor instead.
func (*ShadowingFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{6}
}

func (x *ShadowingFeedbackResponse) GetFeedback() *ShadowingFeedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *ShadowingFeedbackResponse) GetXpEarned() int32 {
	if x != nil {
		return x.XpEarned
	}
	return 0
}

var File_proto_video_proto protoreflect.FileDescriptor

const file_proto_video_proto_rawDesc = "" +
	"\n" +
	"\x11proto/video.proto\x12\rlinguistglass\"F\n" +
	"\x14FindSentencesRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xa2\x01\n" +
	"\x18ShadowingProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aword_id\x18\x02 \x01(\tR\x06wordId\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x02R\baccuracy\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xf7\x01\n" +
	"\tVideoClip\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x05R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x05R\aendTime\x12\x1f\n" +
	"\vsubtitle_en\x18\x06 \x01(\tR\n" +
	"subtitleEn\x12\x1f\n" +
	"\vsubtitle_ru\x18\a \x01(\tR\n" +
	"subtitleRu\x12#\n" +
	"\rthumbnail_url\x18\b \x01(\tR\fthumbnailUrl\"\x84\x01\n" +
	"\x11ShadowingFeedback\x12)\n" +
	"\x10overall_accuracy\x18\x01 \x01(\x02R\x0foverallAccuracy\x12D\n" +
	"\x0fword_accuracies\x18\x02 \x03(\v2\x1b.linguistglass.WordAccuracyR\x0ewordAccuracies\"Z\n" +
	"\fWordAccuracy\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x1a\n" +
	"\baccuracy\x18\x02 \x01(\x02R\baccuracy\x12\x1a\n" +
	"\bfeedback\x18\x03 \x01(\tR\bfeedback\"l\n" +
	"\x15VideoClipListResponse\x12.\n" +
	"\x05clips\x18\x01 \x03(\v2\x18.linguistglass.VideoClipR\x05clips\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x05R\ftotalResults\"v\n" +
	"\x19ShadowingFeedbackResponse\x12<\n" +
	"\bfeedback\x18\x01 \x01(\v2 .linguistglass.ShadowingFeedbackR\bfeedback\x12\x1b\n" +
	"\txp_earned\x18\x02 \x01(\x05R\bxpEarned2\xdd\x01\n" +
	"\fVideoService\x12a\n" +
	"\x14FindSentencesInVideo\x12#.linguistglass.FindSentencesRequest\x1a$.linguistglass.VideoClipListResponse\x12j\n" +
	"\x15SyncShadowingProgress\x12'.linguistglass.ShadowingProgressRequest\x1a(.linguistglass.ShadowingFeedbackResponseB0Z.github.com/mabramyan/langgrpc/go/linguistglassb\x06proto3"

var (
	file_proto_video_proto_rawDescOnce sync.Once
	file_proto_video_proto_rawDescData []byte
)

func file_proto_video_proto_rawDescGZIP() []byte {
	file_proto_video_proto_rawDescOnce.Do(func() {
		file_proto_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_video_proto_rawDesc), len(file_proto_video_proto_rawDesc)))
	})
	return file_proto_video_proto_rawDescData
}

var file_proto_video_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_video_proto_goTypes = []any{
	(*FindSentencesRequest)(nil),      // 0: linguistglass.FindSentencesRequest
	(*ShadowingProgressRequest)(nil),  // 1: linguistglass.ShadowingProgressRequest
	(*VideoClip)(nil),                 // 2: linguistglass.VideoClip
	(*ShadowingFeedback)(nil),         // 3: linguistglass.ShadowingFeedback
	(*WordAccuracy)(nil),              // 4: linguistglass.WordAccuracy
	(*VideoClipListResponse)(nil),     // 5: linguistglass.VideoClipListResponse
	(*ShadowingFeedbackResponse)(nil), // 6: linguistglass.ShadowingFeedbackResponse
}
var file_proto_video_proto_depIdxs = []int32{
	4, // 0: linguistglass.ShadowingFeedback.word_accuracies:type_name -> linguistglass.WordAccuracy
	2, // 1: linguistglass.VideoClipListResponse.clips:type_name -> linguistglass.VideoClip
	3, // 2: linguistglass.ShadowingFeedbackResponse.feedback:type_name -> linguistglass.ShadowingFeedback
	0, // 3: linguistglass.VideoService.FindSentencesInVideo:input_type -> linguistglass.FindSentencesRequest
	1, // 4: linguistglass.VideoService.SyncShadowingProgress:input_type -> linguistglass.ShadowingProgressRequest
	5, // 5: linguistglass.VideoService.FindSentencesInVideo:output_type -> linguistglass.VideoClipListResponse
	6, // 6: linguistglass.VideoService.SyncShadowingProgress:output_type -> linguistglass.ShadowingFeedbackResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_video_proto_init() }
func file_proto_video_proto_init() {
	if File_proto_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_video_proto_rawDesc), len(file_proto_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_video_proto_goTypes,
		DependencyIndexes: file_proto_video_proto_depIdxs,
		MessageInfos:      file_proto_video_proto_msgTypes,
	}.Build()
	File_proto_video_proto = out.File
	file_proto_video_proto_goTypes = nil
	file_proto_video_proto_depIdxs = nil
}
