// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/video.proto

package linguistglass

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VideoService_FindSentencesInVideo_FullMethodName  = "/linguistglass.VideoService/FindSentencesInVideo"
	VideoService_SyncShadowingProgress_FullMethodName = "/linguistglass.VideoService/SyncShadowingProgress"
)

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoServiceClient interface {
	// FindSentencesInVideo finds video clips containing a keyword
	FindSentencesInVideo(ctx context.Context, in *FindSentencesRequest, opts ...grpc.CallOption) (*VideoClipListResponse, error)
	// SyncShadowingProgress syncs shadowing practice results
	SyncShadowingProgress(ctx context.Context, in *ShadowingProgressRequest, opts ...grpc.CallOption) (*ShadowingFeedbackResponse, error)
}

type videoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceClient(cc grpc.ClientConnInterface) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) FindSentencesInVideo(ctx context.Context, in *FindSentencesRequest, opts ...grpc.CallOption) (*VideoClipListResponse, error) {
	out := new(VideoClipListResponse)
	err := c.cc.Invoke(ctx, VideoService_FindSentencesInVideo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) SyncShadowingProgress(ctx context.Context, in *ShadowingProgressRequest, opts ...grpc.CallOption) (*ShadowingFeedbackResponse, error) {
	out := new(ShadowingFeedbackResponse)
	err := c.cc.Invoke(ctx, VideoService_SyncShadowingProgress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServiceServer is the server API for VideoService service.
// All implementations must embed UnimplementedVideoServiceServer
// for forward compatibility
type VideoServiceServer interface {
	// FindSentencesInVideo finds video clips containing a keyword
	FindSentencesInVideo(context.Context, *FindSentencesRequest) (*VideoClipListResponse, error)
	// SyncShadowingProgress syncs shadowing practice results
	SyncShadowingProgress(context.Context, *ShadowingProgressRequest) (*ShadowingFeedbackResponse, error)
	mustEmbedUnimplementedVideoServiceServer()
}

// UnimplementedVideoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVideoServiceServer struct {
}

func (UnimplementedVideoServiceServer) FindSentencesInVideo(context.Context, *FindSentencesRequest) (*VideoClipListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSentencesInVideo not implemented")
}
func (UnimplementedVideoServiceServer) SyncShadowingProgress(context.Context, *ShadowingProgressRequest) (*ShadowingFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncShadowingProgress not implemented")
}
func (UnimplementedVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {}

// UnsafeVideoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceServer will
// result in compilation errors.
type UnsafeVideoServiceServer interface {
	mustEmbedUnimplementedVideoServiceServer()
}

func RegisterVideoServiceServer(s grpc.ServiceRegistrar, srv VideoServiceServer) {
	s.RegisterService(&VideoService_ServiceDesc, srv)
}

func _VideoService_FindSentencesInVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSentencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).FindSentencesInVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_FindSentencesInVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).FindSentencesInVideo(ctx, req.(*FindSentencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_SyncShadowingProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShadowingProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).SyncShadowingProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_SyncShadowingProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).SyncShadowingProgress(ctx, req.(*ShadowingProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoService_ServiceDesc is the grpc.ServiceDesc for VideoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linguistglass.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindSentencesInVideo",
			Handler:    _VideoService_FindSentencesInVideo_Handler,
		},
		{
			MethodName: "SyncShadowingProgress",
			Handler:    _VideoService_SyncShadowingProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/video.proto",
}
